# Chaos Testing Configuration
# This file configures all aspects of chaos testing for RedForge

version: "1.0"

# Global settings
global_seed: null  # Set for reproducible tests
debug_mode: false
dry_run: false
fail_fast: false

# Mutation testing configuration
mutation:
  enabled: true
  types:
    - "data_corruption"
    - "protocol_violation" 
    - "security_payloads"
    - "boundary_testing"
  intensity: 0.3  # 30% mutation rate
  seed: null
  custom_payloads: []
  excluded_types: []

# Chaos replay testing configuration  
chaos_replay:
  enabled: true
  scenarios:
    - "malformed_spans"
    - "network_partition"
    - "memory_pressure"
    - "slow_network"
    - "timeout_chaos"
  duration: 120  # seconds
  intensity: 0.3
  concurrent_scenarios: 3
  recovery_timeout: 30.0

# Span mutation testing configuration
span_mutation:
  enabled: true
  malformation_rate: 0.8
  target_fields:
    - "trace_id"
    - "span_id" 
    - "operation_name"
    - "tags"
    - "logs"
    - "status"
  excluded_malformations: []
  max_nesting_depth: 200

# Gork generation testing configuration
gork_generation:
  enabled: true
  corruption_rate: 0.9
  categories:
    - "binary_corruption"
    - "encoding_corruption"
    - "protocol_corruption"
    - "compression_corruption"
  severity_filter: null  # null, "high", "medium", "low"
  excluded_types:
    - "compression_bomb"  # Exclude in CI to avoid resource issues

# Reporting and metrics configuration
reporting:
  enabled: true
  formats:
    - "json"
    - "text"
    - "csv"
  output_path: "./test-results"
  include_historical: true
  retention_days: 30
  compliance_frameworks:
    - "NIST_AI_RMF"
    - "EU_AI_ACT" 
    - "SOC2"
    - "ISO27001"

# Environment-specific configurations
environments:
  development:
    intensity_multiplier: 1.0
    resource_limits:
      memory: "2Gi"
      cpu: "1000m"
      disk: "10Gi"
      network_bandwidth: "100Mbps"
    disabled_scenarios: []
    timeout_multiplier: 1.0
    parallel_workers: 4

  staging:
    intensity_multiplier: 0.7
    resource_limits:
      memory: "4Gi"
      cpu: "2000m" 
      disk: "20Gi"
      network_bandwidth: "500Mbps"
    disabled_scenarios:
      - "compression_bomb"
    timeout_multiplier: 1.2
    parallel_workers: 6

  production:
    intensity_multiplier: 0.3
    resource_limits:
      memory: "8Gi"
      cpu: "4000m"
      disk: "50Gi" 
      network_bandwidth: "1Gbps"
    disabled_scenarios:
      - "compression_bomb"
      - "buffer_overflow"
      - "memory_exhaustion"
      - "heap_corruption"
      - "stack_corruption"
    timeout_multiplier: 2.0
    parallel_workers: 8

  ci:
    intensity_multiplier: 0.5
    resource_limits:
      memory: "1Gi"
      cpu: "500m"
      disk: "5Gi"
      network_bandwidth: "50Mbps"
    disabled_scenarios:
      - "compression_bomb"
      - "buffer_overflow" 
      - "memory_exhaustion"
      - "long_duration_tests"
    timeout_multiplier: 0.8
    parallel_workers: 2