# RedForge Docker Compose for local development
version: '3.8'

services:
  # CLI Service
  redforge-cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reports:/app/reports
      - ./config:/app/config
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KIT_API_KEY=${KIT_API_KEY}
      - KIT_API_SECRET=${KIT_API_SECRET}
    command: ["python", "-m", "redforge.cli", "--help"]

  # API Gateway Service
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - ENVIRONMENT=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3