apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
  labels:
    name: chaos-testing
    purpose: isolated-chaos-testing
    security-level: testing
  annotations:
    chaos.redforge.io/isolation-level: "high"
    chaos.redforge.io/resource-monitoring: "enabled"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: chaos-testing-quota
  namespace: chaos-testing
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8" 
    limits.memory: 16Gi
    pods: "10"
    persistentvolumeclaims: "5"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: chaos-testing-limits
  namespace: chaos-testing
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "2Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - max:
      cpu: "2000m"
      memory: "4Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container