{{- if and .Values.ingress.enabled .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "promptstrike-sidecar.fullname" . }}-monitoring
  namespace: {{ include "promptstrike-sidecar.namespaceName" . }}
  labels:
    {{- include "promptstrike-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring-ingress
  annotations:
    # Monitoring-specific annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Restrict access to monitoring endpoints
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.monitoring.allowedCIDRs | join "," }}"
    # Rate limiting for metrics endpoints
    nginx.ingress.kubernetes.io/rate-limit: "{{ .Values.ingress.monitoring.rateLimit.requests }}"
    nginx.ingress.kubernetes.io/rate-limit-window: "{{ .Values.ingress.monitoring.rateLimit.window }}"
    # Basic auth for monitoring endpoints
    {{- if .Values.ingress.monitoring.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "promptstrike-sidecar.fullname" . }}-monitoring-auth
    nginx.ingress.kubernetes.io/auth-realm: 'PromptStrike Monitoring'
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.monitoring.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.monitoring.host }}
      secretName: {{ .Values.ingress.monitoring.tlsSecret }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.monitoring.host }}
      http:
        paths:
          - path: /security/metrics
            pathType: Exact
            backend:
              service:
                name: {{ include "promptstrike-sidecar.fullname" . }}
                port:
                  name: http-sidecar
          - path: /health
            pathType: Exact
            backend:
              service:
                name: {{ include "promptstrike-sidecar.fullname" . }}
                port:
                  name: http-sidecar
          - path: /debug/pprof
            pathType: Prefix
            backend:
              service:
                name: {{ include "promptstrike-sidecar.fullname" . }}
                port:
                  name: http-sidecar
{{- end }}