{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "promptstrike-sidecar.fullname" . }}
  namespace: {{ include "promptstrike-sidecar.namespaceName" . }}
  labels:
    {{- include "promptstrike-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  annotations:
    description: "RBAC role for PromptStrike guardrail sidecar"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
# Allow reading only specific ConfigMaps
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["{{ include "promptstrike-sidecar.fullname" . }}-app", "{{ include "promptstrike-sidecar.fullname" . }}-sidecar"]
  verbs: ["get", "watch"]
  
# Allow reading only specific Secrets (for API keys if needed)
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ include "promptstrike-sidecar.fullname" . }}-secrets"]
  verbs: ["get"]
  
# Allow reading own Pod information for self-discovery
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["{{ include "promptstrike-sidecar.fullname" . }}-*"]

# Allow creating Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "promptstrike-sidecar.fullname" . }}
  namespace: {{ include "promptstrike-sidecar.namespaceName" . }}
  labels:
    {{- include "promptstrike-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  annotations:
    description: "RBAC role binding for PromptStrike guardrail sidecar"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "promptstrike-sidecar.serviceAccountName" . }}
  namespace: {{ include "promptstrike-sidecar.namespaceName" . }}
roleRef:
  kind: Role
  name: {{ include "promptstrike-sidecar.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

{{- if .Values.monitoring.enabled }}
---
# Additional ClusterRole for monitoring if needed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "promptstrike-sidecar.fullname" . }}-monitoring
  labels:
    {{- include "promptstrike-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-monitoring
  annotations:
    description: "ClusterRole for PromptStrike monitoring"
rules:
# Allow reading nodes for node-level metrics
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy"]
  verbs: ["get", "list", "watch"]

# Allow reading services and endpoints for service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "promptstrike-sidecar.fullname" . }}-monitoring
  labels:
    {{- include "promptstrike-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-monitoring
subjects:
- kind: ServiceAccount
  name: {{ include "promptstrike-sidecar.serviceAccountName" . }}
  namespace: {{ include "promptstrike-sidecar.namespaceName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "promptstrike-sidecar.fullname" . }}-monitoring
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}