# Chaos Mesh Scenarios for PromptStrike
# 目标：验证 data_corruption 和 protocol_violation 场景下系统韧性

# Data Corruption Scenarios
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: data-corruption-logs
  namespace: promptstrike-test
spec:
  # Target the guardrail sidecar
  selector:
    labelSelectors:
      app: psguard
  # Corrupt log file writes
  action: fault
  path: "/app/logs/*"
  errno: 5  # EIO - Input/output error
  percent: 30  # 30% of I/O operations fail
  duration: "60s"
  
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: data-corruption-reports
  namespace: promptstrike-test
spec:
  # Target report generation
  selector:
    labelSelectors:
      app: psguard
  action: fault
  path: "/var/reports/*"
  errno: 28  # ENOSPC - No space left on device
  percent: 20
  duration: "120s"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: data-corruption-latency
  namespace: promptstrike-test
spec:
  # Add latency to data operations
  selector:
    labelSelectors:
      app: psguard
  action: latency
  path: "/app/data/*"
  delay: "100ms"
  percent: 50
  duration: "180s"

# Protocol Violation Scenarios
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: protocol-violation-partition
  namespace: promptstrike-test
spec:
  # Network partition between sidecar and LLM API
  selector:
    labelSelectors:
      app: psguard
  action: partition
  direction: to
  target:
    selector:
      labelSelectors:
        app: llm-api
  duration: "90s"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: protocol-violation-corrupt
  namespace: promptstrike-test
spec:
  # Corrupt network packets
  selector:
    labelSelectors:
      app: psguard
  action: corrupt
  corrupt:
    percent: "10"
  duration: "120s"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: protocol-violation-duplicate
  namespace: promptstrike-test
spec:
  # Duplicate network packets
  selector:
    labelSelectors:
      app: psguard
  action: duplicate
  duplicate:
    percent: "15"
  duration: "90s"

# Network Delay Scenarios
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-high
  namespace: promptstrike-test
spec:
  # High network latency
  selector:
    labelSelectors:
      app: psguard
  action: delay
  delay:
    latency: "200ms"
    correlation: "25"
    jitter: "10ms"
  duration: "300s"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-variable
  namespace: promptstrike-test
spec:
  # Variable network latency
  selector:
    labelSelectors:
      app: psguard
  action: delay
  delay:
    latency: "50ms"
    correlation: "0"
    jitter: "100ms"
  duration: "240s"

# Pod Failure Scenarios
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-kill
  namespace: promptstrike-test
spec:
  # Kill pods randomly
  selector:
    labelSelectors:
      app: psguard
  action: pod-kill
  gracePeriod: 0
  duration: "60s"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-restart
  namespace: promptstrike-test
spec:
  # Restart containers
  selector:
    labelSelectors:
      app: psguard
  action: container-kill
  containerNames:
    - guardrail-sidecar
  duration: "120s"

# Memory Pressure Scenarios
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-pressure-high
  namespace: promptstrike-test
spec:
  # High memory pressure
  selector:
    labelSelectors:
      app: psguard
  mode: one
  stressors:
    memory:
      workers: 2
      size: "80%"
  duration: "180s"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-pressure-high
  namespace: promptstrike-test
spec:
  # High CPU pressure
  selector:
    labelSelectors:
      app: psguard
  mode: one
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "240s"

# HTTP Chaos for API Testing
---
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-chaos-abort
  namespace: promptstrike-test
spec:
  # Abort HTTP requests
  selector:
    labelSelectors:
      app: psguard
  target: Request
  port: 8001
  method: POST
  path: "/scan"
  abort: true
  duration: "90s"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-chaos-delay
  namespace: promptstrike-test
spec:
  # Delay HTTP responses
  selector:
    labelSelectors:
      app: psguard
  target: Response
  port: 8001
  method: GET
  path: "/health"
  delay: "5s"
  duration: "120s"

# JVM Chaos (if using Java components)
---
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-chaos-gc
  namespace: promptstrike-test
spec:
  # Force garbage collection
  selector:
    labelSelectors:
      app: psguard
  action: gc
  duration: "60s"

# Time Chaos for Clock Skew
---
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: time-chaos-skew
  namespace: promptstrike-test
spec:
  # Clock skew simulation
  selector:
    labelSelectors:
      app: psguard
  timeOffset: "-10m"
  duration: "180s"

# Kernel Chaos for System-Level Faults
---
apiVersion: chaos-mesh.org/v1alpha1
kind: KernelChaos
metadata:
  name: kernel-chaos-io
  namespace: promptstrike-test
spec:
  # Kernel-level I/O faults
  selector:
    labelSelectors:
      app: psguard
  failKernRequest:
    callchain:
      - funcname: "bio_add_page"
    failtype: 0
  duration: "120s"

# DNS Chaos for Service Discovery Issues
---
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-chaos-failure
  namespace: promptstrike-test
spec:
  # DNS resolution failures
  selector:
    labelSelectors:
      app: psguard
  action: error
  patterns:
    - "*.openai.com"
    - "api.anthropic.com"
  duration: "90s"

# Workflow for Combined Chaos Testing
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: promptstrike-chaos-workflow
  namespace: promptstrike-test
spec:
  entry: data-corruption-phase
  templates:
    - name: data-corruption-phase
      templateType: Serial
      children:
        - data-corruption-logs
        - data-corruption-reports
      deadline: "300s"
      
    - name: protocol-violation-phase
      templateType: Parallel
      children:
        - protocol-violation-partition
        - protocol-violation-corrupt
      deadline: "180s"
      
    - name: recovery-test-phase
      templateType: Serial
      children:
        - network-delay-high
        - pod-failure-restart
      deadline: "240s"

# Schedule for Automated Chaos Testing
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: promptstrike-chaos-schedule
  namespace: promptstrike-test
spec:
  # Run chaos tests every 6 hours
  schedule: "0 */6 * * *"
  historyLimit: 5
  concurrencyPolicy: Forbid
  type: Workflow
  workflowSpec:
    entry: data-corruption-phase
    templates:
      - name: data-corruption-phase
        templateType: Serial
        children:
          - data-corruption-logs
          - protocol-violation-partition
        deadline: "600s"