apiVersion: v1
kind: Namespace
metadata:
  name: promptstrike-guardrail
  labels:
    name: promptstrike-guardrail
    app.kubernetes.io/name: promptstrike-guardrail
    app.kubernetes.io/component: security-monitoring
    app.kubernetes.io/part-of: promptstrike