{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "promptstrike-sidecar.fullname" . }}-hpa
  namespace: {{ include "promptstrike-sidecar.namespaceName" . }}
  labels:
    {{- include "promptstrike-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: autoscaling
  annotations:
    description: "Horizontal Pod Autoscaler for PromptStrike guardrail sidecar"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "promptstrike-sidecar.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.hpa.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.hpa.customMetrics }}
  {{- range .Values.hpa.customMetrics }}
  - type: Pods
    pods:
      metric:
        name: {{ .name }}
        selector:
          matchLabels:
            {{- include "promptstrike-sidecar.selectorLabels" $ | nindent 12 }}
      target:
        type: AverageValue
        averageValue: {{ .targetValue }}
  {{- end }}
  {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.hpa.behavior.scaleUp.percentPolicy }}
        periodSeconds: {{ .Values.hpa.behavior.scaleUp.periodSeconds }}
      - type: Pods
        value: {{ .Values.hpa.behavior.scaleUp.podsPolicy }}
        periodSeconds: {{ .Values.hpa.behavior.scaleUp.periodSeconds }}
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.hpa.behavior.scaleDown.percentPolicy }}
        periodSeconds: {{ .Values.hpa.behavior.scaleDown.periodSeconds }}
      - type: Pods
        value: {{ .Values.hpa.behavior.scaleDown.podsPolicy }}
        periodSeconds: {{ .Values.hpa.behavior.scaleDown.periodSeconds }}
      selectPolicy: Min
{{- end }}