{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "redforge-sidecar.fullname" . }}-limits
  namespace: {{ include "redforge-sidecar.namespaceName" . }}
  labels:
    {{- include "redforge-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: resource-management
  annotations:
    description: "Default resource limits and requests for RedForge guardrail sidecar"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}