{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "redforge-sidecar.fullname" . }}-pdb
  namespace: {{ include "redforge-sidecar.namespaceName" . }}
  labels:
    {{- include "redforge-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: availability
  annotations:
    description: "Ensures minimum availability during cluster maintenance"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "redforge-sidecar.selectorLabels" . | nindent 6 }}
{{- end }}