{{- if .Values.rbac.enterprise.enabled }}
# Enterprise RBAC Roles
{{- range .Values.rbac.enterprise.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "redforge-sidecar.fullname" $ }}-{{ .name }}
  namespace: {{ include "redforge-sidecar.namespaceName" $ }}
  labels:
    {{- include "redforge-sidecar.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rbac-enterprise
    rbac.redforge.io/role: {{ .name }}
  annotations:
    description: {{ .description | quote }}
    rbac.redforge.io/permissions: {{ .permissions | join "," | quote }}
spec:
  rules:
  {{- if has "read:reports" .permissions }}
  # Report reading permissions
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: 
      - "{{ include "redforge-sidecar.fullname" $ }}-reports"
      - "{{ include "redforge-sidecar.fullname" $ }}-compliance"
    verbs: ["get", "list"]
  {{- end }}
  
  {{- if has "generate:reports" .permissions }}
  # Report generation permissions
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: 
      - "{{ include "redforge-sidecar.fullname" $ }}-reports"
      - "{{ include "redforge-sidecar.fullname" $ }}-compliance"
    verbs: ["get", "list", "create", "update", "patch"]
  {{- end }}
  
  {{- if has "view:metrics" .permissions }}
  # Metrics access permissions
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    resourceNames: ["{{ include "redforge-sidecar.fullname" $ }}"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
    resourceNames: ["{{ include "redforge-sidecar.fullname" $ }}-*"]
  {{- end }}
  
  {{- if has "access:health" .permissions }}
  # Health check permissions
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["{{ include "redforge-sidecar.fullname" $ }}"]
    verbs: ["get"]
  {{- end }}
  
  {{- if has "write:config" .permissions }}
  # Configuration management permissions
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: 
      - "{{ include "redforge-sidecar.fullname" $ }}-app"
      - "{{ include "redforge-sidecar.fullname" $ }}-sidecar"
    verbs: ["get", "list", "create", "update", "patch"]
  {{- end }}
  
  {{- if has "manage:keys" .permissions }}
  # Secret management permissions
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ include "redforge-sidecar.fullname" $ }}-secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
  {{- end }}
  
  {{- if has "view:audit-logs" .permissions }}
  # Audit log access permissions
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  {{- end }}
  
  {{- if has "export:compliance" .permissions }}
  # Compliance export permissions
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    resourceNames: ["{{ include "redforge-sidecar.fullname" $ }}-exports"]
    verbs: ["get", "list", "create"]
  {{- end }}
  
  {{- if has "test:endpoints" .permissions }}
  # Testing permissions
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["{{ include "redforge-sidecar.fullname" $ }}"]
    verbs: ["get", "create"]
  {{- end }}
  
  {{- if has "manage:rbac" .permissions }}
  # RBAC management permissions
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "patch"]
  {{- end }}
  
  {{- if has "admin:all" .permissions }}
  # Administrative permissions
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  {{- end }}

{{- end }}

# Enterprise User Role Bindings
{{- range .Values.rbac.enterprise.userBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "redforge-sidecar.fullname" $ }}-{{ .role }}-{{ .user | replace "@" "-at-" | replace "." "-" }}
  namespace: {{ include "redforge-sidecar.namespaceName" $ }}
  labels:
    {{- include "redforge-sidecar.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rbac-enterprise
    rbac.redforge.io/binding-type: user
    rbac.redforge.io/role: {{ .role }}
  annotations:
    rbac.redforge.io/user: {{ .user | quote }}
    rbac.redforge.io/managed-by: "helm"
subjects:
- kind: User
  name: {{ .user }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "redforge-sidecar.fullname" $ }}-{{ .role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

# Enterprise Service Account Role Bindings
{{- range .Values.rbac.enterprise.serviceAccountBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "redforge-sidecar.fullname" $ }}-{{ .role }}-{{ .serviceAccount }}
  namespace: {{ .namespace | default (include "redforge-sidecar.namespaceName" $) }}
  labels:
    {{- include "redforge-sidecar.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rbac-enterprise
    rbac.redforge.io/binding-type: serviceaccount
    rbac.redforge.io/role: {{ .role }}
  annotations:
    rbac.redforge.io/service-account: {{ .serviceAccount | quote }}
    rbac.redforge.io/managed-by: "helm"
subjects:
- kind: ServiceAccount
  name: {{ .serviceAccount }}
  namespace: {{ .namespace | default (include "redforge-sidecar.namespaceName" $) }}
roleRef:
  kind: Role
  name: {{ include "redforge-sidecar.fullname" $ }}-{{ .role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

# Enterprise Service Accounts
{{- range .Values.rbac.enterprise.serviceAccountBindings }}
{{- if not (has .serviceAccount $.Values.rbac.enterprise.existingServiceAccounts) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount }}
  namespace: {{ .namespace | default (include "redforge-sidecar.namespaceName" $) }}
  labels:
    {{- include "redforge-sidecar.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rbac-enterprise
    rbac.redforge.io/service-account: {{ .serviceAccount }}
  annotations:
    rbac.redforge.io/role: {{ .role | quote }}
    rbac.redforge.io/managed-by: "helm"
automountServiceAccountToken: true
{{- end }}
{{- end }}

{{- if .Values.rbac.enterprise.customRoles }}
# Custom RBAC Role Template
# Use this as a template for creating custom roles
# Copy and modify in your values.yaml under rbac.enterprise.roles
---
# Example Custom Role (commented out by default)
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: {{ include "redforge-sidecar.fullname" . }}-custom-role
#   namespace: {{ include "redforge-sidecar.namespaceName" . }}
#   labels:
#     {{- include "redforge-sidecar.labels" . | nindent 4 }}
#     app.kubernetes.io/component: rbac-custom
# spec:
#   rules:
#   - apiGroups: [""]
#     resources: ["configmaps"]
#     verbs: ["get", "list"]
#   - apiGroups: [""]
#     resources: ["services"]
#     verbs: ["get"]
{{- end }}

{{- end }}