apiVersion: v1
kind: Service
metadata:
  name: {{ include "redforge-sidecar.fullname" . }}
  namespace: {{ include "redforge-sidecar.namespaceName" . }}
  labels:
    {{- include "redforge-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  annotations:
    {{- if .Values.monitoring.prometheus.enabled }}
    prometheus.io/scrape: "{{ .Values.monitoring.prometheus.scrape }}"
    prometheus.io/port: "{{ .Values.monitoring.prometheus.port }}"
    prometheus.io/path: "{{ .Values.monitoring.prometheus.path }}"
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.app.enabled }}
    - port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
      protocol: TCP
      name: http-app
    {{- end }}
    {{- if .Values.sidecar.enabled }}
    - port: {{ .Values.service.sidecar.port }}
      targetPort: {{ .Values.service.sidecar.targetPort }}
      protocol: TCP
      name: http-sidecar
    {{- end }}
  selector:
    {{- include "redforge-sidecar.selectorLabels" . | nindent 4 }}